# Generated by Django 4.1.1 on 2022-09-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genus', models.ManyToManyField(to='reptileglossaryapi.genus')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeedsReptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('morph', models.ManyToManyField(to='reptileglossaryapi.morph')),
                ('species', models.ManyToManyField(to='reptileglossaryapi.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeedsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publishing_date', models.DateField(auto_now_add=True)),
                ('specialneedsreptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.specialneedsreptile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.writer')),
            ],
        ),
        migrations.CreateModel(
            name='ReptileGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publishing_date', models.DateField(auto_now_add=True)),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.reptile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.writer')),
            ],
        ),
        migrations.CreateModel(
            name='ReptileDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('diet', models.ManyToManyField(to='reptileglossaryapi.diet')),
                ('reptile', models.ManyToManyField(to='reptileglossaryapi.reptile')),
            ],
        ),
        migrations.AddField(
            model_name='reptile',
            name='species',
            field=models.ManyToManyField(to='reptileglossaryapi.species'),
        ),
        migrations.CreateModel(
            name='DietGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publishing_date', models.DateField(auto_now_add=True)),
                ('reptilediet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.reptilediet')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptileglossaryapi.writer')),
            ],
        ),
    ]
