# Generated by Django 4.1.1 on 2022-09-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptileglossaryapi', '0002_dietguide_image_reptileguide_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietguide',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='reptileguide',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='specialneedsguide',
            name='publishing_date',
        ),
    ]
